SELECT
    'DROP SEQUENCE ' || SEQUENCE_NAME || ';' || CHR(13) ||
    --CREATE SEQUENCE  "ITSM2"."FOMM_ATCHFILE_MT_FILE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100261 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    'CREATE SEQUENCE "' || SEQUENCE_NAME || '" MIN_VALUE ' || MIN_VALUE || ' MAX_VALUE ' || MAX_VALUE || ' INCREMENT BY ' || INCREMENT_BY || ' START WITH ' || (LAST_NUMBER + 1) || ' CACHE ' || CACHE_SIZE ||
    CASE WHEN ORDER_FLAG = 'N' THEN ' NOORDER ' END ||
    CASE WHEN CYCLE_FLAG = 'N' THEN ' NOCYCLE ' END ||
    CASE WHEN KEEP_VALUE = 'N' THEN ' NOKEEP ' END ||
    CASE WHEN 	SCALE_FLAG = 'N' THEN ' NOSCALE ' END || ' GLOBAL;' AS SCRIPT
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME NOT LIKE '%$%';


SELECT
	  REQ_ID
	, REQ_TMPLAT_ID
	, WF_PROC_CD
	, WF_PROC_NM
	, MAP_WF_PROC_CD
	, MAP_WF_PROC_NM
	, REQ_STAT_CD
	, REQ_STAT_NM
FROM SR_BASE_INFO AS OF TIMESTAMP(SYSTIMESTAMP-INTERVAL '5' MINUTE)
WHERE REQ_ID = ''

AS OF TIMESTAMP(SYSTIMESTAMP-INTERVAL '5' MINUTE);

SELECT
	'SELECT' || CHR(13) ||
    '    ' || LISTAGG(CASE WHEN DATA_TYPE IN ('BLOB', 'CLOB') THEN 'NULL AS ' END || COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_ID) ||
	'FROM ' || TABLE_NAME || CHR(13) ||
	'WHERE 1 = 1' || CHR(13) ||
	'AND ' AS QUERY
FROM
    (
    SELECT
        TABLE_NAME,
        COLUMN_ID,
        COLUMN_NAME,
        CASE
            WHEN DATA_TYPE IN ('VARCHAR2', 'NVARCHAR2', 'CHAR') THEN 'VARCHAR'
            WHEN DATA_TYPE IN ('NUMBER', 'FLOAT', 'LONG') THEN 'NUMBER'
            ELSE DATA_TYPE
        END DATA_TYPE,
        DATA_DEFAULT
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = 'WF_CHM_WORK_HIST'
    )
GROUP BY TABLE_NAME
;

SELECT
      LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_ID)
FROM
    SYS.ALL_TAB_COLUMNS@PDB

WHERE 1 = 1
AND TABLE_NAME = UPPER('TBT_SR_SATI_EXM')
;

SELECT
      OWNER
    , TABLE_NAME
    , COMMENTS
FROM
    SYS.ALL_TAB_COMMENTS

WHERE 1 = 1
AND TABLE_TYPE  = 'TABLE'
AND OWNER = 'ITSM'
AND TABLE_NAME NOT LIKE '%$%'
AND TABLE_NAME NOT LIKE '%EDM%'

ORDER BY
    TABLE_NAME
;

SELECT
      A.TABLE_NAME,
      A.COLUMN_NAME

FROM
      ALL_TAB_COLUMNS A

WHERE 1 = 1
AND A.COLUMN_NAME LIKE '%' || 'CSR_GRADE' || '%'

ORDER BY A.COLUMN_ID
;

SELECT
      A.COLUMN_NAME
    , CASE WHEN A.COLUMN_ID > 1 THEN ', ' ELSE '  ' END || A.COLUMN_NAME  AS COL
    , DATA_TYPE ||
      CASE WHEN DATA_TYPE <> 'CLOB' THEN '(' END ||
      CASE
        WHEN DATA_TYPE <> 'CLOB'
        THEN
          CASE
            WHEN DATA_TYPE = 'NUMBER'
            THEN DATA_PRECISION
            ELSE DATA_LENGTH
          END
      END ||
      CASE
        WHEN DATA_TYPE <> 'CLOB'
        THEN CASE WHEN DATA_TYPE = 'NUMBER' AND DATA_SCALE > 0 THEN ', ' || DATA_SCALE  END
      END ||
      CASE WHEN DATA_TYPE <> 'CLOB' THEN ')' END   AS DATA_TYPE
    , B.COMMENTS

FROM
      ALL_TAB_COLUMNS A
    , USER_COL_COMMENTS B

WHERE 1 = 1
AND A.TABLE_NAME    = B.TABLE_NAME
AND A.COLUMN_NAME   = B.COLUMN_NAME
AND A.TABLE_NAME    = UPPER('WF_APPROVAL_MT')   --WF_REG_TBL_IFNO_DT

ORDER BY A.COLUMN_ID
;


SELECT
    '/* ' || 'CODE_DIV:[' || CODE_DIV || '] ' ||
    (SELECT CMM_CD_NM || '[' || CMM_CD || ']' FROM FOMM_CMM_CD_MT WHERE CMM_CD = A.UP_CMM_CD) || ' - ' || CD_NM || ' */'  AS CODE_INFO
FROM
    (
    SELECT
          CODE_DIV 
        , UP_CMM_CD
        , LISTAGG(CMM_CD || ':[' || CMM_CD_NM || ']', ', ') WITHIN GROUP (ORDER BY SORT_ORDR)   AS CD_NM
    FROM FOMM_CMM_CD_MT
    WHERE 1 = 1
    AND UP_CMM_CD   = 'SR_MST_MAPPING_CD'
    AND USE_YN      = 'Y'
    GROUP BY CODE_DIV, UP_CMM_CD
    ) A
;
--TABLE INSERT HEADER
SELECT
    (
    SELECT
        'INSERT INTO ' || TABLE_NAME || '(' || 
        LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || ')' AS COL_LIST
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = A.TNAME
    GROUP BY
        TABLE_NAME
    ) AS INSERT_QUERY
FROM
    TAB A
WHERE 1 = 1
AND A.TNAME NOT LIKE 'BIN%'
AND A.TABTYPE   = 'TABLE'
AND A.TNAME     = &TBL_NM
;

--TABLE INSERT DATA


--TABLE SELECT INSERT 쿼리 생성
SELECT
    (
    SELECT
        'INSERT INTO ' || TABLE_NAME || CHR(13)||CHR(10) ||
        '(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
        LISTAGG(COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) ||
        ')' || CHR(13)||CHR(10) ||
        
        'SELECT' || CHR(13)||CHR(10) || 
        CHR(9) || '  ' ||
        
        LISTAGG(COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) ||
        
        'FROM ' || TABLE_NAME || &END_NAME || CHR(13)||CHR(10) || ';'
        AS COL_LIST
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = A.TNAME
    GROUP BY
        TABLE_NAME
    ) AS INSERT_QUERY
FROM
    TAB A
WHERE 1 = 1
AND A.TNAME NOT LIKE 'BIN%'
AND A.TABTYPE   = 'TABLE'
AND A.TNAME     = &TBL_NM
;

--prepared
SELECT
    (
    SELECT
        'INSERT INTO ' || TABLE_NAME || CHR(13)||CHR(10) ||
        '(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
        LISTAGG(COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) ||
        ')' || CHR(13)||CHR(10) ||
        
        'VALUES(' || CHR(13)||CHR(10) || 
        CHR(9) || '  ' ||
        
        LISTAGG('?', CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) ||
        
        ')' --'FROM ' || TABLE_NAME || &END_NAME || CHR(13)||CHR(10) || ';'
        AS COL_LIST
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = A.TNAME
    GROUP BY
        TABLE_NAME
    ) AS INSERT_QUERY
FROM
    TAB A
WHERE 1 = 1
AND A.TNAME NOT LIKE 'BIN%'
AND A.TABTYPE   = 'TABLE'
AND A.TNAME     = &TBL_NM



-- TABLE CRUD 쿼리 생성
SELECT
    (
    SELECT
        'SELECT ' || CHR(13)||CHR(10) || CHR(9) || '  ' || '''' || '0' || '''' || CHR(9) || 'AS CHK' ||
        CHR(13)||CHR(10) || CHR(9) || ', ' || '''''' || CHR(9) || 'AS ROWFLAG' || CHR(13)||CHR(10) || CHR(9) ||
        ', ' || LISTAGG('A.' || COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||
        'FROM' || CHR(13)||CHR(10) || CHR(9) || TABLE_NAME || ' A ' || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||
        'WHERE 1 = 1' || CHR(13)||CHR(10) ||
        'AND ' ||
        (
        SELECT LISTAGG(E.COLUMN_NAME || ' = ' || '#' || '{' || E.COLUMN_NAME || '}', CHR(13)||CHR(10) || 'AND ') WITHIN GROUP (ORDER BY E.POSITION) AS PK_COLS
        FROM    
        ALL_CONSTRAINTS  D,
        ALL_CONS_COLUMNS E
        WHERE 1 = 1
        AND D.OWNER           = E.OWNER
        AND D.CONSTRAINT_NAME = E.CONSTRAINT_NAME
        AND D.TABLE_NAME      = B.TABLE_NAME
        AND D.CONSTRAINT_TYPE = 'P'
        --AND E.COLUMN_NAME     = 'REQ_ID'
        )
    FROM ALL_TAB_COLUMNS B
    WHERE TABLE_NAME = A.TNAME
    GROUP BY
        TABLE_NAME
    )   AS SELECT_QUERY,
    (
    SELECT
        'INSERT INTO ' || TABLE_NAME || CHR(13)||CHR(10) ||
        '(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
        LISTAGG(COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) ||
        ')' || CHR(13)||CHR(10) ||
        'VALUES' || CHR(13)||CHR(10) || 
        '(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
        LISTAGG(
            CASE
                WHEN COLUMN_NAME IN ('FRID', 'LMID') THEN '#' || '{LMID}'
                WHEN COLUMN_NAME IN ('FR_USER_NM', 'LM_USER_NM') THEN '(SELECT USER_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME IN ('FR_DEPT_CD', 'LM_DEPT_CD') THEN '(SELECT DEPT_CD FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME IN ('FR_DEPT_NM', 'LM_DEPT_NM') THEN '(SELECT DEPT_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME IN ('FRDT', 'LMDT') THEN 'TO_CHAR(SYSDATE, ''YYYYMMDDHH24MISS'')'
                ELSE '#' || '{' || COLUMN_NAME || '}'
            END
            , CHR(13)||CHR(10) || CHR(9) || ', '
        ) WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) || ')' AS COL_LIST
    FROM ALL_TAB_COLUMNS
    WHERE TABLE_NAME = A.TNAME
    GROUP BY
        TABLE_NAME
    ) AS INSERT_QUERY,
    (
    SELECT
        'UPDATE ' || TABLE_NAME || ' SET ' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
        LISTAGG(
            COLUMN_NAME || ' = ' ||
            CASE
                WHEN COLUMN_NAME = 'LM_USER_NM' THEN '(SELECT USER_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME = 'LM_DEPT_CD' THEN '(SELECT DEPT_CD FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME = 'LM_DEPT_NM' THEN '(SELECT DEPT_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
                WHEN COLUMN_NAME = 'LMDT' THEN 'TO_CHAR(SYSDATE, ''YYYYMMDDHH24MISS'')'
                ELSE '#' || '{' || COLUMN_NAME || '}'
            END        
            , CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || ' ' || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||

        'WHERE 1 = 1' || CHR(13)||CHR(10) ||
        'AND ' ||
        (
        SELECT LISTAGG(E.COLUMN_NAME || ' = ' || '#' || '{' || E.COLUMN_NAME || '}', CHR(13)||CHR(10) || 'AND ') WITHIN GROUP (ORDER BY E.POSITION) AS PK_COLS
        FROM    
        ALL_CONSTRAINTS  D,
        ALL_CONS_COLUMNS E
        WHERE 1 = 1
        AND D.OWNER           = E.OWNER
        AND D.CONSTRAINT_NAME = E.CONSTRAINT_NAME
        AND D.TABLE_NAME      = B.TABLE_NAME
        AND D.CONSTRAINT_TYPE = 'P'
        ) AS QUERY
    FROM ALL_TAB_COLUMNS B
    WHERE 1 = 1
    AND TABLE_NAME = A.TNAME
    AND COLUMN_NAME NOT IN ('FRID', 'FR_USER_NM', 'FR_DEPT_CD', 'FR_DEPT_NM', 'FRDT')
    AND NOT EXISTS
                (
                SELECT 1
                FROM    
                ALL_CONSTRAINTS  D,
                ALL_CONS_COLUMNS E
                WHERE 1 = 1
                AND D.OWNER             = E.OWNER
                AND D.CONSTRAINT_NAME   = E.CONSTRAINT_NAME
                AND D.CONSTRAINT_TYPE   = 'P'
                AND D.TABLE_NAME        = B.TABLE_NAME
                AND E.COLUMN_NAME       = B.COLUMN_NAME
                )

    GROUP BY
        TABLE_NAME
    ) AS UPDATE_QUERY,
    'DELETE' || CHR(13)||CHR(10) ||
    'FROM ' || TNAME || ' ' || CHR(13)||CHR(10) ||
    'WHERE 1 = 1' || CHR(13)||CHR(10) ||
    'AND ' ||
    (
    SELECT LISTAGG(E.COLUMN_NAME || ' = ' || '#' || '{' || E.COLUMN_NAME || '}', CHR(13)||CHR(10) || CHR(13) || 'AND ') WITHIN GROUP (ORDER BY E.POSITION) AS PK_COLS
        FROM    
        ALL_CONSTRAINTS  D,
        ALL_CONS_COLUMNS E
        WHERE 1 = 1
        AND D.OWNER           = E.OWNER
        AND D.CONSTRAINT_NAME = E.CONSTRAINT_NAME
        AND D.TABLE_NAME      = A.TNAME
        AND D.CONSTRAINT_TYPE = 'P'
     )  AS DELETE_QUERY
FROM
    TAB A
WHERE 1 = 1
AND A.TNAME NOT LIKE 'BIN%'
AND A.TABTYPE   = 'TABLE'
AND A.TNAME     = &TBL_NM
;


--CRUD TABLE MYBATIS QUERY 생성
SELECT
	(
	SELECT
		'SELECT ' || CHR(13)||CHR(10) ||
		CHR(9) || '  ' || '''' || '0' || ''''	|| CHR(9) || 'AS CHK' || CHR(13)||CHR(10) || 
		CHR(9) || ', ' || '''' || '''' || CHR(9) || 'AS ROWFLAG' || CHR(13)||CHR(10) || CHR(9) || ', ' || 
		LISTAGG('A.' || COLUMN_NAME, CHR(13)||CHR(10) || CHR(9) || ', ') WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||
		'FROM' || CHR(13)||CHR(10) || CHR(9) || TABLE_NAME || ' A ' || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||
		'WHERE 1 = 1'
	FROM ALL_TAB_COLUMNS
	WHERE TABLE_NAME = :TBL_NM
	GROUP BY
		TABLE_NAME
	)   AS SELECT_QUERY
	,
   DBMS_LOB.SUBSTR((
	SELECT
		'INSERT INTO ' || TABLE_NAME || CHR(13)||CHR(10) ||
		'(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
		XMLAGG(XMLELEMENT(A, (COLUMN_NAME || CHR(13)||CHR(10) || CHR(9) || ', ')) ORDER BY COLUMN_ID).EXTRACT('//text()').GETCLOBVAL() || CHR(13)||CHR(10) ||
		')' || CHR(13)||CHR(10) ||
		'VALUES' || CHR(13)||CHR(10) || 
		'(' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
		XMLAGG(XMLELEMENT(A,
			CASE
				WHEN COLUMN_NAME IN ('FRID', 'LMID') THEN '#' || '{LMID}'
				WHEN COLUMN_NAME IN ('FR_USER_NM', 'LM_USER_NM') THEN '(SELECT USER_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME IN ('FR_DEPT_CD', 'LM_DEPT_CD') THEN '(SELECT DEPT_CD FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME IN ('FR_DEPT_NM', 'LM_DEPT_NM') THEN '(SELECT DEPT_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME IN ('FRDT', 'LMDT') THEN 'TO_CHAR(SYSDATE, ''YYYYMMDDHH24MISS'')'
				ELSE '#' || '{' || COLUMN_NAME || '}'
			END
			|| CHR(13)||CHR(10) || CHR(9) || ', ') ORDER BY COLUMN_ID).EXTRACT('//text()').GETCLOBVAL() || CHR(13)||CHR(10) || ')'

	FROM ALL_TAB_COLUMNS
	WHERE TABLE_NAME = :TBL_NM
	GROUP BY
		TABLE_NAME
	), 4000, 1 ) AS INSERT_QUERY
	,
   DBMS_LOB.SUBSTR( (
	SELECT
		'UPDATE ' || TABLE_NAME || ' SET ' || CHR(13)||CHR(10) || CHR(9) || '  ' ||
		XMLAGG(XMLELEMENT(A,
			COLUMN_NAME || ' = ' ||
			CASE
				WHEN COLUMN_NAME = 'LM_USER_NM' THEN '(SELECT USER_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME = 'LM_DEPT_CD' THEN '(SELECT DEPT_CD FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME = 'LM_DEPT_NM' THEN '(SELECT DEPT_NM FROM FOMM_USER_MT WHERE USER_ID = #' || '{LMID})'
				WHEN COLUMN_NAME = 'LMDT' THEN 'TO_CHAR(SYSDATE, ''YYYYMMDDHH24MISS'')'
				ELSE '#' || '{' || COLUMN_NAME || '}'
			END        
			|| CHR(13)||CHR(10) || CHR(9) || ', ') ORDER BY COLUMN_ID).EXTRACT('//text()').GETCLOBVAL() || ' ' || CHR(13)||CHR(10) || CHR(13)||CHR(10) ||
		'WHERE 1 = 1' || CHR(13)||CHR(10) ||
		'AND ' ||
		(
		SELECT XMLAGG(XMLELEMENT(A, (E.COLUMN_NAME || ' = ' || '#' || '{' || E.COLUMN_NAME || '}' || CHR(13)||CHR(10) || 'AND ')) ORDER BY E.POSITION).EXTRACT('//text()').GETCLOBVAL() AS PK_COLS
		FROM    
		ALL_CONSTRAINTS  D,
		ALL_CONS_COLUMNS E
		WHERE 1 = 1
		AND D.OWNER           = E.OWNER
		AND D.CONSTRAINT_NAME = E.CONSTRAINT_NAME
		AND D.TABLE_NAME      = B.TABLE_NAME
		AND D.CONSTRAINT_TYPE = 'P'
		) AS QUERY
	FROM ALL_TAB_COLUMNS B
	WHERE 1 = 1
	AND TABLE_NAME = :TBL_NM
	AND COLUMN_NAME NOT IN ('FRID', 'FR_USER_NM', 'FR_DEPT_CD', 'FR_DEPT_NM', 'FRDT')
	AND NOT EXISTS
				(
				SELECT 1
				FROM    
				ALL_CONSTRAINTS  D,
				ALL_CONS_COLUMNS E
				WHERE 1 = 1
				AND D.OWNER             = E.OWNER
				AND D.CONSTRAINT_NAME   = E.CONSTRAINT_NAME
				AND D.CONSTRAINT_TYPE   = 'P'
				AND D.TABLE_NAME        = B.TABLE_NAME
				AND E.COLUMN_NAME       = B.COLUMN_NAME
				)

	GROUP BY
		TABLE_NAME
	), 4000, 1 ) AS UPDATE_QUERY
	,
	'DELETE' || CHR(13)||CHR(10) ||
	'FROM ' || :TBL_NM || ' ' || CHR(13)||CHR(10) ||
	'WHERE 1 = 1' || CHR(13)||CHR(10) ||
	'AND ' ||
	(
	SELECT LISTAGG(E.COLUMN_NAME || ' = ' || '#' || '{' || E.COLUMN_NAME || '}', CHR(13)||CHR(10) || CHR(13) || 'AND ') WITHIN GROUP (ORDER BY E.POSITION) AS PK_COLS
		FROM    
		ALL_CONSTRAINTS  D,
		ALL_CONS_COLUMNS E
		WHERE 1 = 1
		AND D.OWNER           = E.OWNER
		AND D.CONSTRAINT_NAME = E.CONSTRAINT_NAME
		AND D.TABLE_NAME      = :TBL_NM
		AND D.CONSTRAINT_TYPE = 'P'
	 )  AS DELETE_QUERY

FROM
	DUAL A
WHERE 1 = 1
;




--DB LOCK 조회
SELECT A.OS_USER_NAME, A.ORACLE_USERNAME, B.OBJECT_NAME, B.OWNER, B.OBJECT_TYPE, A.XIDUSN, A.SESSION_ID, A.LOCKED_MODE    
FROM
	V$LOCKED_OBJECT A,
    V$SESSION C,
	DBA_OBJECTS B
WHERE 1 = 1
AND A.OBJECT_ID     = B.OBJECT_ID
AND A.SESSION_ID    = C.SID
;

SELECT DISTINCT D.OWNER, X.SESSION_ID, A.SERIAL#, D.OBJECT_NAME, A.MACHINE, A.TERMINAL, A.PROGRAM, B.ADDRESS, B.PIECE, B.SQL_TEXT
FROM
	V$LOCKED_OBJECT X,
	V$SESSION A,
	V$SQLTEXT B,
	DBA_OBJECTS D

WHERE 1 = 1
AND X.SESSION_ID = A.SID
AND X.OBJECT_ID	= D.OBJECT_ID
AND A.SQL_ADDRESS = B.ADDRESS
ORDER BY B.ADDRESS, B.PIECE
;

--ALTER SYSTEM KILL SESSION '1928, 3029';