package com.base.fwk.server;

public class Constants {

	public static final String ENCODING = "UTF-8";
	public static final String NEW_LENE = System.lineSeparator();
	public static final String FILESEPARATOR = "/";
	
	public static final String TAG_COMMA = "%2C";
	public static final String TAG_SPACE = "%20";
	public static final String TAG_EQ = "%3D";
	public static final String TAG_LT = "%3C";
	public static final String TAG_GT = "%3E";
	public static final String TAG_QT = "%22";
	public static final String TAG_OPEN_BRACKET = "%28";
	public static final String TAG_CLOSE_BRACKET = "%29";

	//Dao 기본 Templete
	public static final String DAO_TEMPLETE = "package com.base.#0.dao;\r\n"
			+ "\r\n"
			+ "import java.util.List;\r\n"
			+ "import java.util.Map;\r\n"
			+ "import org.springframework.stereotype.Repository;\r\n"
			+ "\r\n"
			+ "/**\r\n"
			+ " * \r\n"
			+ " * <pre>\r\n"
			+ " * @title\r\n"
			+ " * - #2 DAO\r\n"
			+ " * @package com.base.#0.dao\r\n"
			+ " * <pre>\r\n"
			+ " *\r\n"
			+ " * @author  #3\r\n"
			+ " * @since   #4\r\n"
			+ " * @version 1.0\r\n"
			+ " * @see\r\n"
			+ " *\r\n"
			+ " * =================== 변경 내역 ==================\r\n"
			+ " * 날짜			변경자				내용\r\n"
			+ " * ------------------------------------------------\r\n"
			+ " * #4	#3		최초작성\r\n"
			+ " */\r\n"
			+ "@Repository\r\n"
			+ "public interface #1DAO {\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 목록 조회\r\n"
			+ "	 * @param dsCond\r\n"
			+ "	 * @return\r\n"
			+ "	 */\r\n"
			+ "	public List<Map<String, Object>> select01(Map<String, Object> dsCond);\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 저장\r\n"
			+ "	 * @param rowData\r\n"
			+ "	 */\r\n"
			+ "	public void insert01(Map<String, Object> rowData);\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 수정\r\n"
			+ "	 * @param rowData\r\n"
			+ "	 */\r\n"
			+ "	public void modify01(Map<String, Object> rowData);\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 삭제\r\n"
			+ "	 * @param rowData\r\n"
			+ "	 */\r\n"
			+ "	public void remove01(Map<String, Object> rowData);\r\n"
			+ "}";

	//Service 기본 Templete
	public static final String SERVICE_TEMPLETE = "package com.base.#0.service;\r\n"
			+ "\r\n"
			+ "import java.util.List;\r\n"
			+ "import java.util.Map;\r\n"
			+ "\r\n"
			+ "/**\r\n"
			+ " * \r\n"
			+ " * <pre>\r\n"
			+ " * @title\r\n"
			+ " * - #2 Service Intreface\r\n"
			+ " * @package com.base.#0.service\r\n"
			+ " * <pre>\r\n"
			+ " *\r\n"
			+ " * @author  #3\r\n"
			+ " * @since   #4\r\n"
			+ " * @version 1.0\r\n"
			+ " * @see\r\n"
			+ " *\r\n"
			+ " * =================== 변경 내역 ==================\r\n"
			+ " * 날짜			변경자				내용\r\n"
			+ " * ------------------------------------------------\r\n"
			+ " * #4	#3		최초작성\r\n"
			+ " */\r\n"
			+ "public interface #1Service {\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 목록 조회\r\n"
			+ "	 * @param dsCond\r\n"
			+ "	 * @return\r\n"
			+ "	 */\r\n"
			+ "	public List<Map<String, Object>> select01(Map<String, Object> dsCond);\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 저장\r\n"
			+ "	 * @param dsData\r\n"
			+ "	 */\r\n"
			+ "	public void save01(List<Map<String, Object>> dsData);\r\n"
			+ "}";

	//ServiceImpl 기본 Templete
	public static final String SERVICEIMPL_TEMPLETE = "package com.base.#0.service.impl;\r\n"
			+ "\r\n"
			+ "import java.util.List;\r\n"
			+ "import java.util.Map;\r\n"
			+ "import jakarta.inject.Inject;\r\n"
			+ "import jakarta.inject.Provider;\r\n"
			+ "import org.springframework.beans.factory.annotation.Autowired;\r\n"
			+ "import org.springframework.transaction.annotation.Transactional;\r\n"
			+ "import org.springframework.stereotype.Service;\r\n"
			+ "import com.base.com.vo.SessionContext;\r\n"
			+ "import com.base.fwk.util.StringUtil;\r\n"
			+ "import com.base.#0.dao.#1DAO;\r\n"
			+ "import com.base.#0.service.#1Service;\r\n"
			+ "\r\n"
			+ "/**\r\n"
			+ " * \r\n"
			+ " * <pre>\r\n"
			+ " * @title\r\n"
			+ " * - #2 Service(구현체)\r\n"
			+ " * @package com.base.#0.service.impl\r\n"
			+ " * <pre>\r\n"
			+ " *\r\n"
			+ " * @author  #3\r\n"
			+ " * @since   #4\r\n"
			+ " * @version 1.0\r\n"
			+ " * @see\r\n"
			+ " *\r\n"
			+ " * =================== 변경 내역 ==================\r\n"
			+ " * 날짜			변경자				내용\r\n"
			+ " * ------------------------------------------------\r\n"
			+ " * #4	#3		최초작성\r\n"
			+ " */\r\n"
			+ "@Service\r\n"
			+ "public class #1ServiceImpl implements #1Service {\r\n"
			+ "\r\n"
			+ "	@Inject\r\n"
			+ "	private Provider<SessionContext> sc;\r\n"
			+ "\r\n"
			+ "	@Autowired\r\n"
			+ "	private #1DAO #5Dao;\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 목록 조회\r\n"
			+ "	 */\r\n"
			+ "	public List<Map<String, Object>> select01(Map<String, Object> dsCond) {\r\n"
			+ "		List<Map<String, Object>> result = #5Dao.select01(dsCond);\r\n"
			+ "		return result;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 저장\r\n"
			+ "	 */\r\n"
			+ "	@Transactional\r\n"
			+ "	public void save01(List<Map<String, Object>> dsData) {\r\n"
			+ "\r\n"
			+ "		String userId 	= sc.get().getScUserId();\r\n"
			+ "		String lmpId 	= sc.get().getScLmpId();\r\n"
			+ "\r\n"
			+ "		for (int i = 0; i < dsData.size(); i++) {\r\n"
			+ "			Map<String, Object> rowData = dsData.get(i);\r\n"
			+ "\r\n"
			+ "	        // DATA RowType 가져오기\r\n"
			+ "	    	String rowFlag = StringUtil.safe(rowData.get(\"ROWFLAG\"));\r\n"
			+ "	    	rowData.put(\"LMID\", userId);\r\n"
			+ "	    	rowData.put(\"LMPID\", lmpId);\r\n"
			+ "\r\n"
			+ "	    	if(\"I\".equals(rowFlag)) {\r\n"
			+ "	    		#5Dao.insert01(rowData);\r\n\r\n"
			+ "	    	}else if(\"U\".equals(rowFlag)) {\r\n"
			+ "	    		#5Dao.modify01(rowData);\r\n\r\n"
			+ "	    	}else if(\"D\".equals(rowFlag)) {\r\n"
			+ "	    		#5Dao.remove01(rowData);\r\n"
			+ "	    	}\r\n"
			+ "		}\r\n"
			+ "	}\r\n"
			+ "}";
	
	//Controller 기본 Templete
	public static final String CONTROLLER_TEMPLETE = "package com.base.#0.web;\r\n"
			+ "\r\n"
			+ "import java.util.List;\r\n"
			+ "import java.util.Map;\r\n"
			+ "import org.slf4j.Logger;\r\n"
			+ "import org.slf4j.LoggerFactory;\r\n"
			+ "import org.springframework.beans.factory.annotation.Autowired;\r\n"
			+ "import org.springframework.stereotype.Controller;\r\n"
			+ "import org.springframework.web.bind.annotation.RequestMapping;\r\n"
			+ "import com.nexacro.uiadapter.jakarta.core.NexacroException;\r\n"
			+ "import com.nexacro.uiadapter.jakarta.core.annotation.ParamDataSet;\r\n"
			+ "import com.nexacro.uiadapter.jakarta.core.data.NexacroResult;\r\n"
			+ "import com.base.#0.service.#1Service;\r\n"
			+ "import com.base.com.service.FommAuthService;\r\n"
			+ "\r\n"
			+ "/**\r\n"
			+ " * \r\n"
			+ " * <pre>\r\n"
			+ " * @title\r\n"
			+ " * - #2 Controller\r\n"
			+ " * @package com.base.#0.web\r\n"
			+ " * <pre>\r\n"
			+ " *\r\n"
			+ " * @author  #3\r\n"
			+ " * @since   #4\r\n"
			+ " * @version 1.0\r\n"
			+ " * @see\r\n"
			+ " *\r\n"
			+ " * =================== 변경 내역 ==================\r\n"
			+ " * 날짜			변경자				내용\r\n"
			+ " * ------------------------------------------------\r\n"
			+ " * #4	#3		최초작성\r\n"
			+ " */\r\n"
			+ "@Controller\r\n"
			+ "@RequestMapping(\"#1\")\r\n"
			+ "public class #1Controller {\r\n"
			+ "\r\n"
			+ "	private Logger log = LoggerFactory.getLogger(#1Controller.class);\r\n"
			+ "\r\n"
			+ "	@Autowired\r\n"
			+ "	private #1Service #5Svc;\r\n"
			+ "\r\n"
			+ "	@Autowired\r\n"
			+ "	private FommAuthService fommAuthSvc;\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 목록 조회\r\n"
			+ "	 * @param dsCond\r\n"
			+ "	 * @return\r\n"
			+ "	 */\r\n"
			+ "	@RequestMapping(\"/select01\")\r\n"
			+ "	public NexacroResult select01(@ParamDataSet(name = \"dsCond\") Map<String, Object> dsCond) throws NexacroException {\r\n"
			+ "\r\n"
			+ "		NexacroResult result = new NexacroResult();\r\n\r\n"
			+ "		List<Map<String, Object>> dsData = #5Svc.select01(dsCond);\r\n"
			+ "		result.addDataSet(\"dsData\", dsData);\r\n"
			+ "		return result;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	/**\r\n"
			+ "	 * #2 저장\r\n"
			+ "	 * @param dsData\r\n"
			+ "	 * @return\r\n"
			+ "	 */\r\n"
			+ "	@RequestMapping(value = \"/save01\")\r\n"
			+ "	public NexacroResult save01(@ParamDataSet(name = \"dsCond\") Map<String, Object> dsCond, @ParamDataSet(name = \"dsData\") List<Map<String, Object>> dsData) throws Exception \r\n"
			+ "	{\r\n"
			+ "		// 요청 메뉴 권한 확인\r\n"
			+ "		NexacroResult result = fommAuthSvc.getMenuAuth(\"SAVE_YN\");\r\n"
			+ "\r\n"
			+ "		if( result.getVariables().get(\"AUTH_YN\").equals(\"Y\") ) {\r\n"
			+ "\r\n"
			+ "			#5Svc.save01(dsData);\r\n"
			+ "		}else {\r\n"
			+ "\r\n"
			+ "			return result;\r\n"
			+ "		}"
			+ "\r\n"
			+ "		dsData = #5Svc.select01(dsCond);\r\n"
			+ "		result.addDataSet(\"dsData\", dsData);\r\n"
			+ "		return result;\r\n"
			+ "	}\r\n"
			+ "}";

		//Controller 기본 Templete
		public static final String MAPPER_TEMPLETE =
			"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
			+ "<!DOCTYPE mapper PUBLIC \"-//mybatis.org//DTD Mapper 3.0//EN\" \r\n"
			+ "\"http://mybatis.org/dtd/mybatis-3-mapper.dtd\">\r\n"
			+ "\r\n"
			+ "<mapper namespace=\"com.wemb.spp.#0.dao.#1DAO\">\r\n"
			+ "\r\n"
			+ "	<select id=\"select01\" parameterType=\"java.util.Map\" resultType=\"java.util.Map\">\r\n"
			+ "	</select>\r\n"
			+ "\r\n"
			+ "	<insert id=\"insert01\" parameterType=\"java.util.Map\">\r\n"
			+ "	</insert>\r\n"
			+ "\r\n"
			+ "	<update id=\"modify01\" parameterType=\"java.util.Map\">\r\n"
			+ "	</update>\r\n"
			+ "\r\n"
			+ "	<delete id=\"remove01\" parameterType=\"java.util.Map\">\r\n"
			+ "	</delete>\r\n"
			+ "\r\n"
			+ "</mapper>";
}